### ISSUE TITLE
could you tell me about model name thermal printer receipt?

### ISSUE THREAD

**Issue by ul-rotha** [kakzaki/blue_thermal_printer#1]
could you tell me about model name thermal printer receipt?

**Comment by kakzaki** [comment]
it works on different kind of bluetooth thermal printer

I myself using SmartLogic MP-58X Mobile Bluetooth Thermal Printer, You can use another brand as long as it is bluetooth thermal printer with 58 x 40mm paper

**Comment by ul-rotha** [comment]
Thanks for reply. I hope when I face problem have u to help.

Best Regards.

**Comment by NivethaMuthukumar** [comment]
for me printing not working, it's connected successfully.

**printer model is** : `tsc alpha-3r bluetooth printer`
