### ISSUE TITLE
Error on bluetooth.connect(_device)

### ISSUE THREAD

**Issue by andersondn** [kakzaki/blue_thermal_printer#10]
I`m getting this error below

`Exception has occurred.
PlatformException (PlatformException(connect_error, read failed, socket might closed or timeout, read ret: -1, java.io.IOException: read failed, socket might closed or timeout, read ret: -1
	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:741)
	at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:753)
	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:375)
	at id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin.lambda$connect$0(BlueThermalPrinterPlugin.java:343)
	at id.kakzaki.blue_thermal_printer.-$$Lambda$BlueThermalPrinterPlugin$JxnBuByWzwnPoLoXadcl8ktG62Q.run(lambda)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
))`

**Comment by cahyowhy** [comment]
i have this issue too

**Comment by cahyowhy** [comment]
just try this on _connectBluetooth method. its solve the issue

```
void _connectBluetooth() {
    if (_device == null) {
      Scaffold.of(context).showSnackBar(new SnackBar(
        content: new Text('No device selected.'),
      ));
    } else {
      _bluetooth.isConnected.then((isConnected) async {
        if (!isConnected) {
          try {
            await _bluetooth.connect(_device);
          } on PlatformException catch (e) {
            debugPrint(e.toString());
            Scaffold.of(context).showSnackBar(new SnackBar(
              content: new Text("Failed to connect bluetooth. Try to restart the thermal printer and connect again"),
            ));

            setState(() => _bluetoothPressed = false);
          }

          setState(() => _bluetoothPressed = true);
        }
      });
    }
  }
```

**Comment by jiwaraga06** [comment]
> just try this on _connectBluetooth method. its solve the issue
> 
> ```
> void _connectBluetooth() {
>     if (_device == null) {
>       Scaffold.of(context).showSnackBar(new SnackBar(
>         content: new Text('No device selected.'),
>       ));
>     } else {
>       _bluetooth.isConnected.then((isConnected) async {
>         if (!isConnected) {
>           try {
>             await _bluetooth.connect(_device);
>           } on PlatformException catch (e) {
>             debugPrint(e.toString());
>             Scaffold.of(context).showSnackBar(new SnackBar(
>               content: new Text("Failed to connect bluetooth. Try to restart the thermal printer and connect again"),
>             ));
> 
>             setState(() => _bluetoothPressed = false);
>           }
> 
>           setState(() => _bluetoothPressed = true);
>         }
>       });
>     }
>   }
> ```

i try it but its not working :((
