### ISSUE TITLE
A value of type 'Object?' can't be assigned to a variable of type 'BluetoothDevice'.

### ISSUE THREAD

**Issue by Unlaytsabxwb** [kakzaki/blue_thermal_printer#100]
Expanded(
                      child: DropdownButton(
                        items: _getDeviceItems(),
                        onChanged: (value) => setState(() => _device = value),
                        value: _device,
                      ),
                    ),
A value of type 'Object?' can't be assigned to a variable of type 'BluetoothDevice'.

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
