### ISSUE TITLE
build fails for web

### ISSUE THREAD

**Issue by raaone7** [kakzaki/blue_thermal_printer#103]
we get the below error 
```
Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: lib/generated_plugin_registrant.dart:8:8:
Error: Error when reading '../.pub-cache/hosted/pub.dartlang.org/blue_thermal_printer-1.1.8/lib/': Error reading '../.pub-cache/hosted/pub.dartlang.org/blue_thermal_printer-1.1.8/lib/'  (Is a directory)
import 'package:blue_thermal_printer/';
       ^
lib/generated_plugin_registrant.dart:23:3:
Error: Undefined name 'BlueThermalPrinterPlugin'.
  BlueThermalPrinterPlugin.registerWith(registrar);
  ^^^^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
Compiling lib/main.dart for the Web...                             32.2s
Exception: Failed to compile application for the Web.
```

**Comment by VetrivelDevOps** [comment]
It won't build for web. Try to run using Mobile debug (or) with mobile emulators

**Comment by jessp01** [comment]
Hi all,

The reason for the failure is https://github.com/kakzaki/blue_thermal_printer/blob/master/pubspec.yaml#L34
To make `flutter build web` work, you can just comment out/remove lines 34 and 35.

Making it actually work in web context is a bigger job. For starters, you'd need to change that section as follows:
```yaml
         web:
            pluginClass: BlueThermalPrinter
            fileName: blue_thermal_printer.dart
```
But then, you'd get this error:
```err
Target dart2js failed: Exception: lib/generated_plugin_registrant.dart:42:22:
Error: Method not found: 'BlueThermalPrinter.registerWith'.
  BlueThermalPrinter.registerWith(registrar);
                     ^^^^^^^^^^^^
Error: Compilation failed.
```

And indeed, that `registerWith()` method is not implemented and the platform interface package does not exist.
More info on that can be found here:
https://www.section.io/engineering-education/writing-a-flutter-web-plugin/

At this point, I don't need BT printing in web context (and I'm not even sure whether that can technically work) so I shan't pursue it further but if the author is seeing this, I'd suggest you either check whether this is even feasible and if so, implement that interface, or remove the `web` section from `pubspec.yaml` so it at least doesn't fail the web build.

Cheers,

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
