### ISSUE TITLE
App crash after printing image

### ISSUE THREAD

**Issue by erwinw97** [kakzaki/blue_thermal_printer#105]
Hi im currently using blue_thermal version 1.1.7
and everytime i try to print an image ( with 300pixel x 300pixel ) the flutter app crashed .
If someone here have some solution/ experience the same issue as me, i would like to know how to solve  this

**Comment by erwinw97** [comment]
it also happen on version 1.1.8 , i make a new flutter app with same code as given by example on this repository.
the connection works fine then the app always crash after printing 1 time

**Comment by pablo-souza** [comment]
I have the same problem, but it doesn't happen with all printer models.
I had problem with the Leopard printer

**Comment by pablo-souza** [comment]
print on the BG-58P printer

**Comment by erwinw97** [comment]
@pablo-souza i currently have a workaround. since its not working on current version. I use version 1.1.4 and it works fine on my side now

**Comment by pablo-souza** [comment]
@erwinw97 , I use this version too

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
