### ISSUE TITLE
Error in example app: getBluetoothService() called with no BluetoothManagerCallback

### ISSUE THREAD

**Issue by HarryAtSaltus** [kakzaki/blue_thermal_printer#109]
In the example app,  when I select my bluetooth printer and click the 'Connect' button this error occurs:
W/BluetoothAdapter(18987): getBluetoothService() called with no BluetoothManagerCallback

**Comment by HarryAtSaltus** [comment]
As far as I know, this issue has not been resolved.  I gave up on this package and switched to a package called Printing.

**Comment by amit-onappr** [comment]
@HarryAtSaltus Is Printing Plugin works for bluetooth?

**Comment by HarryAtSaltus** [comment]
@amit-onappr Yes, the Printing package prints to my bluetooth printer.  Make sure the printer is setup first.  Then test it by printing something that is not related to your Flutter project.

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
