### ISSUE TITLE
App crash after deconnecting bluetooth device

### ISSUE THREAD

**Issue by webbbox** [kakzaki/blue_thermal_printer#110]
Hi,

I'm testing blue_thermal_printer pugin on an android device. I'm using the sample test (https://pub.dev/packages/blue_thermal_printer/example).
After successfully connect to my bluetooth device, if I deconnect my device, the application crashes

Do you have any ideas please ?

E/AndroidRuntime( 1661): FATAL EXCEPTION: Thread-2
E/AndroidRuntime( 1661): Process: com.akhenis.flutter.myapp1, PID: 1661
E/AndroidRuntime( 1661): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-2
E/AndroidRuntime( 1661): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1280)
E/AndroidRuntime( 1661): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:909)
E/AndroidRuntime( 1661): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
E/AndroidRuntime( 1661): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:384)
E/AndroidRuntime( 1661): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:176)
E/AndroidRuntime( 1661): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:221)
E/AndroidRuntime( 1661): 	at id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin$ConnectedThread.run(BlueThermalPrinterPlugin.java:880)
I/Process ( 1661): Sending signal. PID: 1661 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by hussenIbrahim** [comment]
any updates?
