### ISSUE TITLE
Android 12 incomparable 

### ISSUE THREAD

**Issue by swarup13** [kakzaki/blue_thermal_printer#112]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1451, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.redoq.kuick.ccapp/com.merchant.restaurants.dineorder.app.MainActivity}: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@6fced9d7: AdapterService getBondedDevices

the error is still there even after defining the permissions

**Comment by ebrahimmansur** [comment]
Im facing the same problem, is there a solution?

**Comment by coyksdev** [comment]
Facing this issue also

**Comment by mahmoud-atef-eden** [comment]
any solutions ?

**Comment by ralfazri** [comment]
Facing this issue also, any solution for this?

**Comment by blitzlepe** [comment]
Use [permission_handler ](https://pub.dev/packages/permission_handler).
Also set all necessary permissions in Manifest.xml in Android main folder.
Im using android 12, no problem at all.
