### ISSUE TITLE
an error occurred in generated_plugin_registrant.dart

### ISSUE THREAD

**Issue by tiyan-attirmidzi** [kakzaki/blue_thermal_printer#113]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/YBn9gH7/Untitled-7.png" alt="Untitled-7" border="0"></a>

**Comment by GiridharAlakkadan** [comment]
I am also facing the same issue

**Comment by tiyan-attirmidzi** [comment]
> I am also facing the same issue

just ignore it, it's not a problem that will affect your project

**Comment by bramil29** [comment]
does not compile, indicates that there are errors in the project
