### ISSUE TITLE
Erorr While Build or Run App

### ISSUE THREAD

**Issue by KamalBalah** [kakzaki/blue_thermal_printer#117]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        C:\Users\MM Pc\flutter_appp\build\app\intermediates\incremental\mergeReleaseResources\merged.dir\values-sw٦٠٠dp-v13\values-sw٦٠٠dp-v13.xml: error: invalid configuration 'sw٦٠٠dp-v13'.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        C:\Users\MM Pc\flutter_appp\build\app\intermediates\incremental\mergeReleaseResources\merged.dir\values-h٧٢٠dp-v13\values-h٧٢٠dp-v13.xml: error: invalid configuration 'h٧٢٠dp-v13'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Running Gradle task 'assembleRelease'...                           33.2s
Gradle task assembleRelease failed with exit code 1

**Comment by smile675** [comment]
Min SDK 18??
