### ISSUE TITLE
error in run blue_thermal_printer web 

### ISSUE THREAD

**Issue by engaref2000** [kakzaki/blue_thermal_printer#118]
import 'package:blue_thermal_printer/';
       ^
lib/generated_plugin_registrant.dart:15:3: Error: Undefined name 'BlueThermalPrinterPlugin'.
  BlueThermalPrinterPlugin.registerWith(registrar);
  ^^^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.

**Comment by AlexBarzoiu** [comment]
Any updates? Did you manage to resolve this?

**Comment by tcd93** [comment]
`generated_plugin_registrant.dart` is a file that automatically created when you enable flutter web (`flutter config --enable-web`)

This plugin was not created with web support in mind, but you can do that by
```
flutter create --template=plugin --platforms=web .
```
as per stated in this [doc](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#add-support-for-platforms-in-an-existing-plugin-project)

After that go to this project's `pubspec.yaml` and edit _.flutter.plugin_ as follow:
```diff
  plugin:
    platforms:
      android:
        package: id.kakzaki.blue_thermal_printer
        pluginClass: BlueThermalPrinterPlugin
      ios:
        pluginClass: BlueThermalPrinterPlugin
      web:
-       pluginClass: BlueThermalPrinterPlugin
+       pluginClass: BlueThermalPrinterWeb
+       fileName: blue_thermal_printer_web.dart
```

Run `flutter pub get` again, the auto-generated file should now be correct
