### ISSUE TITLE
Connection status

### ISSUE THREAD

**Issue by 926** [kakzaki/blue_thermal_printer#12]
Connection is ok, but :

- When printer is connected, view does not display that printer is connected
- Printer name does not appear on the drop down
- Connect button shows connect instead of disconnect

**Comment by kakzaki** [comment]
it's just an example view, you can customize it / create it whatever you want, as long as the printer function is ok

**Comment by 926** [comment]
It is indeed functional, but this is desirable to make it clear to everyone how it works.
If we clone, code and submit merge request, will you consider it ?

**Comment by 926** [comment]
Hi @kakzaki,

Just another kudo for the bluetooth plugin,
we tested on low level thermal printer and it also connect, this is indeed, super powerful tool.
Sorry to come back but can we edit view and submit merge request ?

**Comment by kakzaki** [comment]
@926 yes you can, it will be helpful for other
