### ISSUE TITLE
error in running MacOS

### ISSUE THREAD

**Issue by skylastn** [kakzaki/blue_thermal_printer#129]
Launching lib/main.dart on macOS in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `blue_thermal_printer` from `Flutter/ephemeral/.symlinks/plugins/blue_thermal_printer/macos`
    [!] Failed to load 'blue_thermal_printer' podspec: 
    [!] Invalid `blue_thermal_printer.podspec` file: syntax error, unexpected tCONSTANT, expecting end
    ....public_header_files = 'Classes/**/*.h''
    ...                        ^~~~~~~
    /Users/skydeveloper/Documents/Kerja/Me/SkyTronik/skytronik_fe/macos/Flutter/ephemeral/.symlinks/plugins/blue_thermal_printer/macos/blue_thermal_printer.podspec:22: unterminated regexp meets end of file
    /Users/skydeveloper/Documents/Kerja/Me/SkyTronik/skytronik_fe/macos/Flutter/ephemeral/.symlinks/plugins/blue_thermal_printer/macos/blue_thermal_printer.podspec:22: target of repeat operator is not specified: /*.h''
      s.dependency 'FlutterMacOS'
      s.platform = :osx, '10.13'
      s.framework = 'CoreBluetooth'

    end
    /m.

     #  from /Users/skydeveloper/Documents/Kerja/Me/SkyTronik/skytronik_fe/macos/Flutter/ephemeral/.symlinks/plugins/blue_thermal_printer/macos/blue_thermal_printer.podspec:17
     #  -------------------------------------------
     #    s.source_files = 'Classes/**/*''
     >    s.public_header_files = 'Classes/**/*.h''
     #    s.dependency 'FlutterMacOS'
     #  -------------------------------------------

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/abstract_external_source.rb:175:in `rescue in store_podspec'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/abstract_external_source.rb:161:in `store_podspec'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:993:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:972:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:971:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:971:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:970:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Exception: Error running pod install

**Comment by flutter-painter** [comment]
@kakzaki would it be possible to fix 1.1.2 on mac based in on 1.1.9 ?

This yields issues on macos for pubs depending on your repo such as  
https://github.com/andriyoganp/blue_print_pos/

I personnally fixed it by removing in file macos/Flutter/ephemeral/.symlinks/plugins/blue_thermal_printer/pubspec.yaml

This bit :
      macos:
        pluginClass: AudioSessionPlugin 
        
And also removing all macos blue_thermal_printer related code

Thanks and congrats for maintaining this unmatched repo though !
