### ISSUE TITLE
letter B in first line

### ISSUE THREAD

**Issue by felipeescalada** [kakzaki/blue_thermal_printer#133]
Whenever we send to print, it prints the first character the letter B

**Comment by wamphukhom** [comment]
I same like this, B The first print will not show.
![278130701_922250405109464_2231246910960900770_n](https://user-images.githubusercontent.com/4565808/163157276-c3fbdc1c-793f-40b7-b453-cbdcb4e7e54b.jpg)

**Comment by felipeescalada** [comment]
we have commented the paperCut and it worked
