### ISSUE TITLE
Problem in typing Arabic letters

### ISSUE THREAD

**Issue by mahmmd** [kakzaki/blue_thermal_printer#135]
There is a problem in typing Arabic letters
I used the following code to print
`bluetooth.printCustom("HEADER", 3, 1);`
`bluetooth.printCustom("Thank You", 2, 1);`
`bluetooth.printCustom("شكرا لك", 2, 1);`
But this result appears in print
![20220307_204950](https://user-images.githubusercontent.com/24524405/157188734-a958b9b0-d662-4e25-9857-6190b2fef13b.jpg)
How can i solve it?

**Comment by as2a3** [comment]
@mahmmd 
I have the same problem, and can not print images in some printers, Did you find any solving?

**Comment by shanubasheer** [comment]
Me also have the same problem, can anybody help me?

**Comment by mahmmd** [comment]
> @mahmmd I have the same problem, and can not print images in some printers, Did you find any solving?

Use this code to print the image
`final filename = 'yourlogo.png';
    var bytes = await rootBundle.load("assets/images/yourlogo.png");
    String dir = (await getApplicationDocumentsDirectory()).path;
    writeToFile(bytes, '$dir/$filename');
    setState(() {
      pathImage = '$dir/$filename';
    });`

`bluetooth.printImage(pathImage); `

**Comment by as2a3** [comment]
@mahmmd 
It did not work in Sunmi V2s printer.

**Comment by as2a3** [comment]
@mahmmd 

Did you solve Arabic letters problem?

**Comment by mahmmd** [comment]
@as2a3 
Not yet

**Comment by mahmmd** [comment]
@as2a3 @shanubasheer 
I used this method and it worked for me
https://github.com/kakzaki/blue_thermal_printer/issues/82#issuecomment-1048964685
![20220316_001609](https://user-images.githubusercontent.com/24524405/158474507-c908c22b-f2a5-47bb-8512-37fa8096f428.jpg)

**Comment by nabil-ha** [comment]
> @as2a3 @shanubasheer I used this method and it worked for me [#82 (comment)](https://github.com/kakzaki/blue_thermal_printer/issues/82#issuecomment-1048964685) ![20220316_001609](https://user-images.githubusercontent.com/24524405/158474507-c908c22b-f2a5-47bb-8512-37fa8096f428.jpg)

I tried but it didn't work
the first question is do I have to build the screenshot widget? and if so, how did you solve that? how can you build widgets inside methods?

**Comment by nabil-ha** [comment]
> > @as2a3 @shanubasheer I used this method and it worked for me [#82 (comment)](https://github.com/kakzaki/blue_thermal_printer/issues/82#issuecomment-1048964685) ![20220316_001609]
I tried but it didn't work
the first question is do I have to build the screenshot widget? and if so, how did you solve that? how can you build widgets inside methods?

**Comment by nabil-ha** [comment]
> @as2a3 @shanubasheer I used this method and it worked for me [#82 (comment)](https://github.com/kakzaki/blue_thermal_printer/issues/82#issuecomment-1048964685) ![20220316_001609]

I tried this but it didn't work for me, do you have to build screenshot widget for this to work? and if so, how do you build it inside a method ?
