### ISSUE TITLE
print is not complete

### ISSUE THREAD

**Issue by rakafajars** [kakzaki/blue_thermal_printer#138]
how to solve print that is not complete or not appropriate?

the contents of the print should be Mod X, but it only reads X

![image](https://user-images.githubusercontent.com/73903697/159836234-001628fb-7d20-4ed1-a149-af8d596a4663.png)

**Comment by untillnesss** [comment]
I faced the same problem, when I run my app in debug mode, everything runs smoothly. But when I run the releases mode, the printer only partially exits and isn't finished, then it stops.
