### ISSUE TITLE
Everything working but nothing printed out. 

### ISSUE THREAD

**Issue by smile675** [kakzaki/blue_thermal_printer#139]
W/BluetoothAdapter(28904): getBluetoothService() called with no BluetoothManagerCallback
D/BThermalPrinterPlugin(28904): android.bluetooth.device.action.ACL_CONNECTED
I/flutter (28904): bluetooth device state: connected
I/ample.testprin(28904): Waiting for a blocking GC ProfileSaver
I/ample.testprin(28904): WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 15.452ms

and nothing happening.

I tested in SMK-M8 thermal printer

**Comment by YahalomsGuy** [comment]
same here, detailed info about my problem in issue #152
