### ISSUE TITLE
Deprecated  API ??

### ISSUE THREAD

**Issue by patrickegp** [kakzaki/blue_thermal_printer#140]
Launching lib[/main.dart]() on Android SDK built for x86 in debug mode...
lib/main.dart:1
Note: [/Users/patrick/developer/flutter/.pub-cache/hosted/pub.dartlang.org/blue_thermal_printer-1.2.0/android/src/main/java/id/kakzaki/blue_thermal_printer/BlueThermalPrinterPlugin.java]() uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Note: [/Users/patrick/developer/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.12/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java]() uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by joao-moniz** [comment]
Hello I have the same warning when using the library. Does anyone know how to solve it?

BlueThermalPrinterPlugin.java uses or overrides a deprecated API.

**Comment by ramosjorgeluis** [comment]
Hello! I get the same warning:
BlueThermalPrinterPlugin.java uses or overrides a deprecated API.
Anyone knows how to solve it?
