### ISSUE TITLE
Print images problem

### ISSUE THREAD

**Issue by kkooi** [kakzaki/blue_thermal_printer#141]
I use print Image Bytes(bytes) uint8list but the image comes out with unknown characters nonstop.

**Comment by s2yed** [comment]
.

**Comment by YahalomsGuy** [comment]
> s(bytes) uint8list but the image comes out

Same here, I guess it is about the type and content of data the image should have (I think it does not support grayscale images) only full black (0xFFFFFFFF)

**Comment by YahalomsGuy** [comment]
> I use print Image Bytes(bytes) uint8list but the image comes out with unknown characters nonstop.

I am using images print with printImageBytes and noticed that my printer can only handle certain ammound of data to be printed.

Therefore, I have splitted the object I am printing to multiple parts of print, each with its own parts to print ( I have actually imlemented 4 parts, each containing the widget, it's own controller and its own capture.
 simplified example 
`var imgText1 = await screenshotController1.capture(pixelRatio: ratio) ?? Uint8List(0);
                                          bluetooth.printImageBytes(imgText1);
                                          var imgText2 = await screenshotController2.capture(pixelRatio: ratio) ?? Uint8List(0);
                                          bluetooth.printImageBytes(imgText2);
                                          var imgText3 = await screenshotController3.capture(pixelRatio: ratio) ?? Uint8List(0);
                                          bluetooth.printImageBytes(imgText3);
                                          var imgText4 = await screenshotController4.capture(pixelRatio: ratio) ?? Uint8List(0);`
