### ISSUE TITLE
Feature does not meet requirements for background location access

### ISSUE THREAD

**Issue by wamphukhom** [kakzaki/blue_thermal_printer#144]
Hello, google console reject project
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9
  blue_thermal_printer: ^1.2.0
  screenshot: ^1.2.3
  http: ^0.13.4 #http
  image: ^3.1.3
  toggle_switch: ^2.0.1
  font_awesome_flutter: ^10.1.0
  flutter_speed_dial: ^5.1.0
  date_time_picker: ^2.1.0
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  shared_preferences: ^2.0.13
  flutter_barcode_scanner: ^2.0.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.2
  permission_handler: ^9.2.0
(how to fix) thanks.
![999](https://user-images.githubusercontent.com/4565808/165430384-829743a9-1ccc-46c0-908d-aac5eebc257d.png)

![Screenshot](https://user-images.githubusercontent.com/4565808/165429816-1d99eb93-625f-4c10-a5fc-133c31105920.png)

**Comment by kakzaki** [comment]
This plugin does not require background location permission
