### ISSUE TITLE
Image printing does not work

### ISSUE THREAD

**Issue by Denis3107** [kakzaki/blue_thermal_printer#145]
![Снимок экрана 2022-04-27 140728](https://user-images.githubusercontent.com/89261970/165505372-bddb65be-ba8d-4f80-bd25-e210d3ad434e.png)

**Comment by mbagusrd** [comment]
is it solved?

**Comment by kakzaki** [comment]
this is not the correct way to print asset image

please refer to the example app

blob:file:///f485119a-93fc-4c84-a101-fc81fd952ee7
