### ISSUE TITLE
#import "Headers/blue_thermal_printer-umbrella.h" on MacOS

### ISSUE THREAD

**Issue by bayuly94** [kakzaki/blue_thermal_printer#150]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/13174151/171041118-cb48fa86-708c-48bd-983f-d84c33e6ffea.png">

**Comment by utpalruparel** [comment]
hello @bayuly94 have have you solved this?

**Comment by bayuly94** [comment]
> hello @bayuly94 have have you solved this?

no

**Comment by kakzaki** [comment]
I hope this is solved on the latest version

**Comment by utpalruparel** [comment]
It start with new error. 

flutter/.pub-cache/hosted/pub.dartlang.org/blue_thermal_printer-1.2.2/macos/Classes/SwiftBlueThermalPrinterPlugin.swift:8:17: error: cannot find 'Music' in scope
    let music = Music(messenger: registrar.messenger, registrar: registrar)
                ^~~~~
note: Using new build system

**Comment by bayuly94** [comment]
> It start with new error.
> 
> flutter/.pub-cache/hosted/pub.dartlang.org/blue_thermal_printer-1.2.2/macos/Classes/SwiftBlueThermalPrinterPlugin.swift:8:17: error: cannot find 'Music' in scope let music = Music(messenger: registrar.messenger, registrar: registrar) ^~~~~ note: Using new build system

me too

**Comment by A7MeDG0L0L** [comment]
> It start with new error.
> 
> flutter/.pub-cache/hosted/pub.dartlang.org/blue_thermal_printer-1.2.2/macos/Classes/SwiftBlueThermalPrinterPlugin.swift:8:17: error: cannot find 'Music' in scope let music = Music(messenger: registrar.messenger, registrar: registrar) ^~~~~ note: Using new build system

Same !

**Comment by utpalruparel** [comment]
Thanks for new update but there is still error for MacOS...
