### ISSUE TITLE
MissingPluginException(No implementation found for method isDeviceConnected on channel blue_thermal_printer/methods)

### ISSUE THREAD

**Issue by gomcodoctor** [kakzaki/blue_thermal_printer#156]
I am getting

`MissingPluginException(No implementation found for method isDeviceConnected on channel blue_thermal_printer/methods)`

when trying to print on background notification in firebase messaging

**Comment by utpalruparel** [comment]
I think ios is not supported. I also tried  but same error. Any solution?

**Comment by gomcodoctor** [comment]
I am getting on android

**Comment by kyawthiha-android** [comment]
### Android 7.1.2 
`Unhandled Exception: MissingPluginException(No implementation found for method isConnected on channel blue_thermal_printer/methods`

**Comment by gomcodoctor** [comment]
Why it's marked as completed?

**Comment by A7mdlbanna** [comment]
Any updates on this?

**Comment by TarunPal3551** [comment]
`E/flutter (21125): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method state on channel blue_thermal_printer/methods)
E/flutter (21125): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #1      BlueThermalPrinter.onStateChanged.<anonymous closure> (package:blue_thermal_printer/blue_thermal_printer.dart:47:53)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #2      BlueThermalPrinter.onStateChanged (package:blue_thermal_printer/blue_thermal_printer.dart:47:11)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #3      PrinterController.startPrinterService.<anonymous closure> (package:apnabillbook/controllers/printer_controller.dart:2149:46)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): 
E/flutter (21125): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method state on channel blue_thermal_printer/methods)
E/flutter (21125): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #1      BlueThermalPrinter.onStateChanged.<anonymous closure> (package:blue_thermal_printer/blue_thermal_printer.dart:47:53)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #2      BlueThermalPrinter.onStateChanged (package:blue_thermal_printer/blue_thermal_printer.dart:47:11)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #3      PrinterController.startScanPrinter.<anonymous closure> (package:apnabillbook/controllers/printer_controller.dart:301:46)
E/flutter (21125): <asynchronous suspension>`
