### ISSUE TITLE
Hello, thanks for your open source library, I want to know how to set the size of the printed paper, I want to fix 80mm high 75mm width, is there any way to set?

### ISSUE THREAD

**Issue by Tate-zwt** [kakzaki/blue_thermal_printer#178]
Hope to get your reply. Thank you very much!

**Comment by Tate-zwt** [comment]
At present, the length is printed according to the content. I want to fix the width and height

**Comment by Tate-zwt** [comment]
resolved

**Comment by 211666** [comment]
Hi,
I have the same problem with my printer.
Could you explain how you resolved your issue?
