### ISSUE TITLE
Why does the first line printed using this library prefixed with B? Please suggest how to remove it

### ISSUE THREAD

**Issue by prajktachvn** [kakzaki/blue_thermal_printer#18]

**Comment by krishnajiYedlapalli** [comment]
For me also it is printing B at prefix, is there any solution for that

**Comment by kakzaki** [comment]
I am not sure myself if it's the problem with plugin or printer hardware

**Comment by pst9354** [comment]
For me it was the bluetooth.paperCut(); that generates the B.
My printer doesn't support paperCut, so I guess it can't properly parse the command, leaving garbage in the buffer for the next printout.
