### ISSUE TITLE
Failed connect bluetooth

### ISSUE THREAD

**Issue by jiwaraga06** [kakzaki/blue_thermal_printer#183]
read failed, socket might closed or timeout, read ret: -1
E/BThermalPrinterPlugin(16266): java.io.IOException: read failed, socket might closed or timeout, read ret: -1
E/BThermalPrinterPlugin(16266):         at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:952)
E/BThermalPrinterPlugin(16266):         at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:966)
E/BThermalPrinterPlugin(16266):         at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:522)
E/BThermalPrinterPlugin(16266):         at id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin.lambda$connect$1$BlueThermalPrinterPlugin(BlueThermalPrinterPlugin.java:531)
E/BThermalPrinterPlugin(16266):         at id.kakzaki.blue_thermal_printer.-$$Lambda$BlueThermalPrinterPlugin$Ahw9MM_9K6f9UCVqtrNy_jHybcU.run(Unknown Source:6)
E/BThermalPrinterPlugin(16266):         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
E/BThermalPrinterPlugin(16266):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)  
E/BThermalPrinterPlugin(16266):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)  
E/BThermalPrinterPlugin(16266):         at java.lang.Thread.run(Thread.java:1012)

Flutter version : 2.8.0, 2.10.5, 3.7.2
Java jdk version : 11.0.7, 17.

Any one can help me ? i really appreciate that, thank you :)

**Comment by Purevbadar112** [comment]
HI
I have same error. Did you find any solution
