### ISSUE TITLE
can not connect to thermal printer

### ISSUE THREAD

**Issue by toulaoBD** [kakzaki/blue_thermal_printer#188]
void _connect() {
    if (_device == null) {
      show('No device selected.');
    } else {
      bluetooth.isConnected.then((isConnected) {
        if (isConnected==true) {
          bluetooth.connect(_device!).catchError((error) {
            setState(() => _connected = false);
          });
          setState(() => _connected = true);
        }
      });
    }
  }

**Comment by muhd-ameen** [comment]
@kakzaki, getting the same issue while connecting

  void _connect() {
    if (_device != null) {
      bluetooth.isConnected.then((isConnected) {
        if (isConnected == true) {
          show('Device connected!');
          bluetooth.connect(_device!).catchError((error) {
            setState(() => _connected = false);
          });
          setState(() => _connected = true);
        } else {
          show('Device not connected!');
        }
      });
    } else {
      show('No device selected.');
    }
  }

**Comment by ALLY-MAFTAH** [comment]
The example code has logical error in its condition. Replace       ` if (isConnected==true)`       with          `if (isConnected != true) `
