### ISSUE TITLE
Feature Request: iOS support

### ISSUE THREAD

**Issue by nnzfly** [kakzaki/blue_thermal_printer#19]

**Comment by 926** [comment]
Just sharing this here in case other face same problem,
While building on iOS I got : 

 `blue_thermal_printer` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Solved by using the following snippet, from https://github.com/ko2ic/image_downloader/issues/9

```
pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    if s.name == 'YOUR_POD_NAME_HERE'
      s.swift_version = '4.2'
    end
  end
end
```

**Comment by vicenterusso** [comment]
> Just sharing this here in case other face same problem,
> While building on iOS I got :
> 
> `blue_thermal_printer` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
> 
> Solved by using the following snippet, from [ko2ic/image_downloader#9](https://github.com/ko2ic/image_downloader/issues/9)
> 
> ```
> pre_install do |installer|
>   installer.analysis_result.specifications.each do |s|
>     if s.name == 'YOUR_POD_NAME_HERE'
>       s.swift_version = '4.2'
>     end
>   end
> end
> ```

Can you please confirm you got this working on iOS

**Comment by 926** [comment]
Hello Vicente,
This allowed me to get the app built on iOS,
I had no thermal printer to test at that time, I presume it fails printing doesn't it ?

**Comment by jasnicaa** [comment]
It fails probably because it doesn't have support for it. I would take some time in the near future to write down support for iOS.

**Comment by hmawla** [comment]
iOS support would be much appreciated

**Comment by SouengKimmeng** [comment]
It would be great if this library support iOS device.

**Comment by Blackheart8788** [comment]
Hi there guys, still hopeful for iOS support.

my best regards.

**Comment by sidealice** [comment]
still not supported right?
i got error:
Unhandled Exception: MissingPluginException(No implementation found for method isConnected on channel blue_thermal_printer/methods)

**Comment by zynhrus** [comment]
> > still not supported right?
> > i got error:
> > Unhandled Exception: MissingPluginException(No implementation found for method isConnected on channel blue_thermal_printer/methods)
> 
> Same error here. Still not supported on iOS.
> 
> Error: MissingPluginException (MissingPluginException(No implementation found for method isAvailable on channel blue_thermal_printer/methods))

I got that error too in iOS

A few months ago it works fine

Error:
Unhandled Exception: MissingPluginException(No implementation found for method getBondedDevices on channel blue_thermal_printer/methods)

MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
BlueThermalPrinter.getBondedDevices (package:blue_thermal_printer/blue_thermal_printer.dart:65:23)
<asynchronous suspension>

**Comment by flutter-painter** [comment]
I haven't tried any of these new packages but they booth provide support for iOS :

* https://pub.dev/packages/pos_printer_manager
* https://pub.dev/packages/esc_pos_bluetooth

I think we would all rather stick to blue_thermal though

**Comment by necessarylion** [comment]
> still not supported right? i got error: Unhandled Exception: MissingPluginException(No implementation found for method isConnected on channel blue_thermal_printer/methods)

Same error here. both IOS and android

**Comment by flutter-painter** [comment]
@necessarylion android works fine,

both android and iOS are included in :
https://pub.dev/packages/blue_print_pos
which is buildt upon blue_thermal_printer for android
