### ISSUE TITLE
Error, depois que conecta no dispositivo

### ISSUE THREAD

**Issue by gabulsavul** [kakzaki/blue_thermal_printer#2]
Ele consegue escolher da lista, mas quando clico em conectar ele fecha o aplicativo.

`E/BThermalPrinterPlugin(22619): 	at id.kakzaki.blue_thermal_printer.-$$Lambda$BlueThermalPrinterPlugin$JxnBuByWzwnPoLoXadcl8ktG62Q.run(Unknown Source:6)
E/BThermalPrinterPlugin(22619): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/BThermalPrinterPlugin(22619): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/BThermalPrinterPlugin(22619): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/BThermalPrinterPlugin(22619): 	at java.lang.Thread.run(Thread.java:764)
E/BThermalPrinterPlugin(22619): Reply already submitted
E/BThermalPrinterPlugin(22619): java.lang.IllegalStateException: Reply already submitted
E/BThermalPrinterPlugin(22619): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:126)
E/BThermalPrinterPlugin(22619): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/BThermalPrinterPlugin(22619): 	at id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin.lambda$connect$0(BlueThermalPrinterPlugin.java:312)
E/BThermalPrinterPlugin(22619): 	at id.kakzaki.blue_thermal_printer.-$$Lambda$BlueThermalPrinterPlugin$JxnBuByWzwnPoLoXadcl8ktG62Q.run(Unknown Source:6)
E/BThermalPrinterPlugin(22619): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/BThermalPrinterPlugin(22619): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/BThermalPrinterPlugin(22619): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/BThermalPrinterPlugin(22619): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(22619): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(22619): Process: id.kakzaki.blue_thermal_printer_example, PID: 22619
E/AndroidRuntime(22619): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(22619): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:126)
E/AndroidRuntime(22619): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/AndroidRuntime(22619): 	at id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin.lambda$connect$0(BlueThermalPrinterPlugin.java:316)
E/AndroidRuntime(22619): 	at id.kakzaki.blue_thermal_printer.-$$Lambda$BlueThermalPrinterPlugin$JxnBuByWzwnPoLoXadcl8ktG62Q.run(Unknown Source:6)
E/AndroidRuntime(22619): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime(22619): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(22619): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(22619): 	at java.lang.Thread.run(Thread.java:764)
D/ViewRootImpl@c7866d9[MainActivity](22619): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(22619): prepareNavigationBarInfo() DecorView@27cc4a1[MainActivity]
D/InputMethodManager(22619): getNavigationBarColor() -855310
I/Process (22619): Sending signal. PID: 22619 SIG: 9
Lost connection to device.`

**Comment by kakzaki** [comment]
english please :)
