### ISSUE TITLE
i cant use it in background

### ISSUE THREAD

**Issue by Kerolos163** [kakzaki/blue_thermal_printer#204]

**Comment by TarunPal3551** [comment]
Facing same issue while sending command from background notification

`E/flutter (21125): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method state on channel blue_thermal_printer/methods)
E/flutter (21125): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #1      BlueThermalPrinter.onStateChanged.<anonymous closure> (package:blue_thermal_printer/blue_thermal_printer.dart:47:53)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #2      BlueThermalPrinter.onStateChanged (package:blue_thermal_printer/blue_thermal_printer.dart:47:11)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #3      PrinterController.startPrinterService.<anonymous closure> (package:apnabillbook/controllers/printer_controller.dart:2149:46)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): 
E/flutter (21125): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method state on channel blue_thermal_printer/methods)
E/flutter (21125): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #1      BlueThermalPrinter.onStateChanged.<anonymous closure> (package:blue_thermal_printer/blue_thermal_printer.dart:47:53)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #2      BlueThermalPrinter.onStateChanged (package:blue_thermal_printer/blue_thermal_printer.dart:47:11)
E/flutter (21125): <asynchronous suspension>
E/flutter (21125): #3      PrinterController.startScanPrinter.<anonymous closure> (package:apnabillbook/controllers/printer_controller.dart:301:46)
E/flutter (21125): <asynchronous suspension>`
