### ISSUE TITLE
Namespace not specified.

### ISSUE THREAD

**Issue by Shek863** [kakzaki/blue_thermal_printer#208]
What went wrong:
A problem occurred configuring project ':blue_thermal_printer'.
Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by dylanroman03** [comment]
@Shek863  could solve it? I have the same error.

**Comment by MMG606** [comment]
any solution ? got this error after upgrading flutter sdk from 3.24 to  3.27

**Comment by rfuentevilla** [comment]
Hi, I have encountered the same problem. SDK 3.5.3
