### ISSUE TITLE
NullpointerException when using custom Main Application

### ISSUE THREAD

**Issue by wmattei** [kakzaki/blue_thermal_printer#21]
When using a Custom Main Application in Android Manifest: 

```xml
   <application
        android:name=".Application"
```
An exception is throwed when instantiating `BlueThermalPrinterPlugin` because `registrar.activity()` returns `null`

The same problem happens on https://github.com/fluttercommunity/flutter_downloader/issues/52

**Comment by wmattei** [comment]
I made a PR that solves this error. Please take a look @kakzaki

**Comment by wmattei** [comment]
Solved on 1.0.9

**Comment by kakzaki** [comment]
thanks for your contribution
