### ISSUE TITLE
Print on PeriPage 

### ISSUE THREAD

**Issue by MaxLeon** [kakzaki/blue_thermal_printer#22]
Any one knows if this library prints on PeriPage Bluetooth Thermal Printer, i tried many times but i cant print nothing, i can connect to the bluetooth but dont do nothing more.

**Comment by gabrielrodrigodesbesell** [comment]
@MaxLeon in theory yes, because it uses bluetooth to send the bytes to print.
Do you have the command bluetooth.paperCut();?
