### ISSUE TITLE
error: package androidx.core.app does not exist

### ISSUE THREAD

**Issue by nikhilvc** [kakzaki/blue_thermal_printer#24]
while i am running my flutter app its showing error like below.

Launching lib\main.dart on V2 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
C:\flutter\.pub-cache\hosted\pub.dartlang.org\blue_thermal_printer-1.0.8\android\src\main\java\id\kakzaki\blue_thermal_printer\BlueThermalPrinterPlugin.java:13: error: package androidx.core.app does not exist
import androidx.core.app.ActivityCompat;
                        ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\blue_thermal_printer-1.0.8\android\src\main\java\id\kakzaki\blue_thermal_printer\BlueThermalPrinterPlugin.java:14: error: package androidx.core.content does not exist
import androidx.core.content.ContextCompat;
                            ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\blue_thermal_printer-1.0.8\android\src\main\java\id\kakzaki\blue_thermal_printer\BlueThermalPrinterPlugin.java:158: error: cannot find symbol
        ContextCompat.startActivity(registrar.activity(), new Intent(android.provider.Settings.ACTION_BLUETOOTH_SETTINGS),
        ^
  symbol:   variable ContextCompat
  location: class BlueThermalPrinterPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\blue_thermal_printer-1.0.8\android\src\main\java\id\kakzaki\blue_thermal_printer\BlueThermalPrinterPlugin.java:166: error: cannot find symbol
          if (ContextCompat.checkSelfPermission(registrar.activity(),
              ^
  symbol:   variable ContextCompat
  location: class BlueThermalPrinterPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\blue_thermal_printer-1.0.8\android\src\main\java\id\kakzaki\blue_thermal_printer\BlueThermalPrinterPlugin.java:169: error: cannot find symbol
            ActivityCompat.requestPermissions(registrar.activity(),
            ^
  symbol:   variable ActivityCompat
  location: class BlueThermalPrinterPlugin
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':blue_thermal_printer:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s

The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.

Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by kakzaki** [comment]
@nikhilvc  you have to migrate to androidx
