### ISSUE TITLE
gradlew.bat exited abnormally

### ISSUE THREAD

**Issue by sarav21** [kakzaki/blue_thermal_printer#25]
I got this when i run the code:
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\DELL\Desktop\flutter\blue_thermal_printer-master\example\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
  Command: C:\Users\DELL\Desktop\flutter\blue_thermal_printer-master\example\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

Thank you in advance

**Comment by gabrielrodrigodesbesell** [comment]
@sarav21 you try migrate your project to AndroidX?

**Comment by sarav21** [comment]
@gabrielrodrigodesbesell   Thank you for RE, When i try the right click and migrate to AndroidX it says: No Usages Found in the Project
however, the gradle.properties have this line:  android.useAndroidX=true

**Comment by sarav21** [comment]
> @sarav21 you try migrate your project to AndroidX?

Thank you it works,
