### ISSUE TITLE
uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library 

### ISSUE THREAD

**Issue by zemunkh** [kakzaki/blue_thermal_printer#28]
**> /android/app/src/debug/AndroidManifest.xml Error:
>         uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library [:bluetooth_print]**

I stuck on this error in 2 days. I found the solution to this issue.

Open printer_app/android/build.gradle:
Change the following line as lower version.

```
android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 16  // Before it was 18
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}
```

However, I found the solution. I don't understand minSdk problem.

**Comment by edgarsingui** [comment]
Hello, can you send me your project with this library please?  i tried to use the documentation but it didn't work, and i need this lib for my project of the school

**Comment by kakzaki** [comment]
@edgarsingui just clone this repo and run the example
