### ISSUE TITLE
It can't print qr_code or barcode

### ISSUE THREAD

**Issue by pjjy** [kakzaki/blue_thermal_printer#29]
Hello is there any way i can print bar code using this on zebra ez320 because every time i print the result would be a Chinese character. 

* I also change the BarcodeFormat.QR_CODE into BarcodeFormat.CODE_128 (photo below)
![barcode](https://user-images.githubusercontent.com/56106322/71710632-e5163580-2e2f-11ea-9ba9-d9094c35396f.PNG)

and this is the result
![20200103_152824 1](https://user-images.githubusercontent.com/56106322/71710656-ffe8aa00-2e2f-11ea-9286-39aff21bb24c.jpg)

**Comment by pjjy** [comment]
Hello can someone help me figuring this problem.

**Comment by zxj17815** [comment]
hi,I have the same needs as you, and I also use this Bluetooth printer. Now I have encountered the same situation. This is how you solved it in the end

**Comment by bunja-100** [comment]
@zxj17815 @pjjy Anyone of you was able to finally get it working correctly? like getting the barcode printed?

**Comment by pjjy** [comment]
i solved the problem when i use the cpcl lib from the zebra printer

**Comment by bunja-100** [comment]
@pjjy can you please provide me some sample code?

**Comment by pjjy** [comment]
u see the code in zebra printer official website , u can google it anyways

**Comment by 15ground** [comment]
@pjjy Please tell me how u solved this problem. U used lib in code or u config ur Bluetooths printer device bro?
