### ISSUE TITLE
Is thier a way to support images larger than 300 * 300

### ISSUE THREAD

**Issue by abdullah-alimam** [kakzaki/blue_thermal_printer#30]
Please I need to print images larger that 300 * 300 for better resolution.

can I do that from my side or I should wait of update or something?

**Comment by kakzaki** [comment]
if you are using android studio you can directly modify this plugin in  Flutter Plugins directory in your project

**Comment by Aultraminum** [comment]
Could you tell me what is the plugin that need to modify?
Is it this file "BlueThermalPrinterPlugin.java"?
Im sorry. I don't know where I can modify the size in this file.
If you could tell us, it will be great.
Thank you.
