### ISSUE TITLE
Can't print images and QR codes

### ISSUE THREAD

**Issue by Schuyten** [kakzaki/blue_thermal_printer#31]
I'm getting this result when printing images. Any ideas? Also didn't succeed to print a QR code yet. Using the Jolimark TP510 and printing text works fine.
![IMG_20200110_200058](https://user-images.githubusercontent.com/33402413/72178890-2a180a00-33e4-11ea-815e-34d50ce62c62.jpg)

**Comment by saturu** [comment]
Same Problem.

**Comment by kakabreezy-prog** [comment]
any clue? i have the same problem

**Comment by Phincode** [comment]
same problem on intermec pr3

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
