### ISSUE TITLE
App crashed after popup request for location

### ISSUE THREAD

**Issue by NaufalHafizi** [kakzaki/blue_thermal_printer#33]
This plugin request for location. both choice will make the app crashed

**Comment by hatakeshinichi** [comment]
me  too

**Comment by Mekre-A** [comment]
So I managed to get past this error by handling the permission request myself. You can use the library permission_handler on pub.dev to do that. And always make sure you check the permission and not this library cause you will still face the crash if the app loses the permission for location somehow.
