### ISSUE TITLE
Change Font Size and Font Weight

### ISSUE THREAD

**Issue by Mufidzz** [kakzaki/blue_thermal_printer#34]
How can i Change Font Size and Font Weight with this library ?

**Comment by pjjy** [comment]
yeah it is also my problem

**Comment by Blackheart8788** [comment]
hi there, for you to make those chages to your text, use .printCustom() this one has a size option.

**Comment by Mufidzz** [comment]
How about using smaller font from the 0 size ?

**Comment by rudywijaya** [comment]
are there any solution?

**Comment by 792266344** [comment]
> How about using smaller font from the 0 size ?

I browses anthor's code, There is some code like "new byte[] { 0x1b, 'a', 0x02 }" can set fontsize and set content align ,But ,I don't know this code how to work,what's it's work theory？

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
