### ISSUE TITLE
Find internal printers

### ISSUE THREAD

**Issue by Ali-Azmoud** [kakzaki/blue_thermal_printer#35]
Hi  
Is there a way to find internal printers like `PAX POS Terminal` devices? [Here is the official website](https://www.pax.com.cn/)
For example,  [A930](https://www.pax.com.cn/traditionalproducts/info.aspx?itemid=210) has its own internal printer.

**Comment by 792266344** [comment]
My inner device also has this question , but it still can print  although The system setting show me the bluetooth is disconnected and this plugin return the device's connect proprety is false
you can try again

**Comment by luissouza** [comment]
> A930

@Ali-Azmoud do you have some success with this? I have A930 too and i want to find internal printer too, tks!

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
