### ISSUE TITLE
Font Style

### ISSUE THREAD

**Issue by Booitt** [kakzaki/blue_thermal_printer#37]
I'm new on the world of Flutter, but I'm a quick learner. Everything that I was looking for were easy to found and implement. But now I'm needing a way to implement a Blueetooth Printer for my purpose, and I'm founding a lack of that on the Flutter world. After trying everything, the only package that worked so far for me was this one. The only problem is that the fonts are are not smooth for my readers to read.

So, is there a way of changing the font style? Like bold or the shape itself? That's the only package that worked with my printer (MTP-3), and the package is so nice to use. The only thing that is not helping me out is the font styling (and the spacing too, but I kind worked it out with a little bit of boilerplate but ok... xD).

I'll keep searching for ways to solve my problem and I'll be glad to post the answer here to help out anyone else with the same issue.

I'll apreciate any help. Even a little path to head on. Thank you!

**Comment by asepindrak** [comment]
Can you change the font style now? i also need it :+1:  :dancers:

**Comment by Booitt** [comment]
> Can you change the font style now? i also need it 👍 👯

Nah! I ended up using another package that's not perfect too but the font style is so not bad.

But I don't believe they updated it and if they did, I would surely come back to this package.

**Comment by JoanRodri** [comment]
> > Can you change the font style now? i also need it 👍 👯
> 
> Nah! I ended up using another package that's not perfect too but the font style is so not bad.
> 
> But I don't believe they updated it and if they did, I would surely come back to this package.

Could you tell wich package are you using please?

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
