### ISSUE TITLE
QR Code Align

### ISSUE THREAD

**Issue by feriyalsusanto** [kakzaki/blue_thermal_printer#4]
Hello kakzaki,

First of all thank you for this awesome library, and can you add some align setting for qr code or image ?
It would be very useful for printing like ticket etc.

Thank you very much.

**Comment by kakzaki** [comment]
maybe next time i will add those features

**Comment by hmtuan196** [comment]
I've create a PR for this, adding width, height and align for printQRcode.
Please take a look and give your thought @kakzaki.
Thanks.
