### ISSUE TITLE
Confirmed working printer models?

### ISSUE THREAD

**Issue by Gintasz** [kakzaki/blue_thermal_printer#41]
I think it would be a great addition to the documentation of this project to add a list of confirmed working fine printer models. Currently we're looking to integrate receipt printing with flutter app and don't know which printer models would work without bugs with this library.

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
