### ISSUE TITLE
'assembleAarRelease' not found in root project

### ISSUE THREAD

**Issue by 926** [kakzaki/blue_thermal_printer#42]
Task 'assembleAarRelease' not found in root project 'blue_thermal_printer'.

This only happens when I try to flutter run --release

Apart from that debug and build appbundle work fine.

Thanks again for the plugin, super duper useful

**Comment by 926** [comment]
flutter clean does not solve this
Issue is also mentioned here :
https://github.com/flutter/flutter/issues/43704

**Comment by 926** [comment]
sticking to ^1.0.8 allow running in **debug** and building **appbundle**,
Don't know why apk cannot be built, would be convenient

**Comment by 926** [comment]
VS Code could not build apk, but android studio could.
Major gradle upgrade prior to retry.
Learning and proceeding.

**Comment by 926** [comment]
https://flutter.dev/docs/development/androidx-migration

**Comment by 926** [comment]
Hi @kakzaki ,
Sorry to reopen this but anytime try to build in release,
I get

* What went wrong:
Task 'assembleAarRelease' not found in root project 'blue_thermal_printer'.

Other comment is : 

The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.

It works in debug though...

**Comment by hmawla** [comment]
Same problem here, unable to build release APK or flutter run --release

**Comment by 926** [comment]
the apk release is still built despite the error displayed...
