### ISSUE TITLE
cannot print text

### ISSUE THREAD

**Issue by KunakornT** [kakzaki/blue_thermal_printer#44]
When I clicked print test button I got some messages and my printer did not print anything.

I/zygote64(19803): Do partial code cache collection, code=61KB, data=53KB
I/zygote64(19803): After code cache collection, code=60KB, data=53KB
I/zygote64(19803): Increasing code cache capacity to 256KB

my printer model is zenpert 3R20.

**Comment by DenisMrGnusa** [comment]
I've same issue,
my printer is Xprinter BP-428U

**Comment by harshilishere** [comment]
Does anyone has any idea about following printer?

https://www.amazon.in/Wizzit-Xprinter-Rechargeable-Bluetooth-Interface/dp/B08RK2VYQT/ref=sr_1_58?crid=2AN8TZIMUR5E2&dchild=1&keywords=rs232+thermal+printer&qid=1630491971&sprefix=rs232+therm%2Caps%2C280&sr=8-58

**Comment by dtaga** [comment]
I cannot print text too.. This is strange because the image and the qrcode is printed correctly. 
Also I don't have the same issue with another model of printer, all text, images and qr gets printed.
 
What could be the reason?

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
