### ISSUE TITLE
The printer is working but not working with Arabic lang

### ISSUE THREAD

**Issue by Omarhussien61** [kakzaki/blue_thermal_printer#46]

**Comment by danilof** [comment]
@Omarhussien61 Hi, I added new PR with charset support. Maybe is this also solution for you :)

**Comment by danhquyen0109** [comment]
Hi, I have same problem with Vietnamese lang and "charset" doesn't work

**Comment by abozanona** [comment]
@danilof What is the charset for Arabic or any other UTF-8 language?

**Comment by tanlocle0495** [comment]
Hi I tried UTF-8 but it still not working.
