### ISSUE TITLE
Unhandled Exception: setState() called after dispose()

### ISSUE THREAD

**Issue by jasnicaa** [kakzaki/blue_thermal_printer#52]
Hi! Thanks for the library it is simple and works great!

I am new to Flutter and still learning about state and widgets lifecycles, so I need help with this.

I have many print methods in code and after I send a text to the printer I pop out of that screen. I guess that's what's happening when I get this error:

W/BluetoothAdapter(27590): getBluetoothService() called with no BluetoothManagerCallback
D/BThermalPrinterPlugin(27590): android.bluetooth.device.action.ACL_CONNECTED
E/flutter (27590): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: setState() called after dispose(): _PrintReceiptCashScreenState#20d90(lifecycle state: defunct, not mounted)
E/flutter (27590): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (27590): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (27590): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

How to fix it? 

Thanks.

**Comment by jasnicaa** [comment]
So it turns out you should not call _disconnect in dispose method as I did.

**Comment by jasnicaa** [comment]
I had some thoughts on this and removed disconnect from dispose method and it looked like it is working, but its not.

**Comment by kakzaki** [comment]
just wrap your setstate

```
if(mounted){
  setState(() {
                                      
        });
 }
```

**Comment by jasnicaa** [comment]
yeah, I don't have any. I am using your example and every setState is wrapped already. I assumed that popUntil after the print is causing it and I have put a delay after the print statement because I was triggering the connect method with the same button as print.
