### ISSUE TITLE
Camera permission is added after building apk

### ISSUE THREAD

**Issue by saahithyan** [kakzaki/blue_thermal_printer#54]
Following camera permissions are added to android manifest file after building apk.

<uses-permission
        android:name="android.permission.CAMERA" />

    <uses-feature
        android:name="android.hardware.camera"
        android:required="false" />

    <uses-feature
        android:name="android.hardware.camera.front"
        android:required="false" />

    <uses-feature
        android:name="android.hardware.camera.autofocus"
        android:required="false" />

    <uses-feature
        android:name="android.hardware.camera.flash"
        android:required="false" />

**Steps to reproduce**

1. Create a flutter project
2. Add `blue_thermal_printer: ^1.1.1` dependency to `pubspec.yaml`
3. Increase `build.gradle` `minSdkVersion` version to `18` located at `<project_dir>/android/app/build.gradle`
4. Build apk `Build -> Flutter -> Build APK`
5. Analyze apk `Build -> Analyze APK ...` select apk `<project_dir>/build/app/outputs/flutter-apk/app-release.apk`
6. Check `AndroidManifest.xml`

you can see all used permissions.
Why do we need camera permission ? Is it possible to build without camera permission ?
Google is warning while uploading apk to playstore

**Comment by giullianocht** [comment]
How can I remove these permissions?

**Comment by seddik** [comment]
this behavior happens because it depends on com.google.zxing which is used for handeling the QR codes, I've removed the dependency and let the QR go because I don't need it in my app. and the Camera permissions is removed, now the app requires location only (for bluetooth purposes).
