### ISSUE TITLE
Save printer into app

### ISSUE THREAD

**Issue by calimba** [kakzaki/blue_thermal_printer#55]
Hello, how can I save the printer into the app when its connected for the first time.

My printer is a MHT-P28A, work perfectly but in every new invoice I need to connect the printer again

Thank you in advance if somebody can give me a example

**Comment by msandwidi** [comment]
Please try this 
```dart
    final myDevice = BluetoothDevice.fromMap({
      'name': data['name'],
      'address': data['address'],
      'type': data['type']
    });
```

**Comment by calimba** [comment]
> Please try this
> 
> ```dart
>     final myDevice = BluetoothDevice.fromMap({
>       'name': data['name'],
>       'address': data['address'],
>       'type': data['type']
>     });
> ```

Work perfect, thank you so much
