### ISSUE TITLE
Increase Font Size

### ISSUE THREAD

**Issue by Moudy1311** [kakzaki/blue_thermal_printer#56]
Thankyou so much for this contribution.

I was wondering if it would be possible to increase the font size upto 8?  If so, how would I do this?
I'm happy to pay you if youre willing to assist.

Thankyou so much!!!!

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
