### ISSUE TITLE
How to print text in same line for EOS Receipt ?

### ISSUE THREAD

**Issue by Aathi** [kakzaki/blue_thermal_printer#57]
@kakzaki 

I have been trying to print a receipt like below, But I am not able to print item in same line when I use ```bluetooth.printCustom("Body left",1,0); bluetooth.printCustom("Body right",1,2); ``` I have tried  different ways to print  exactly  EOS Receipt but couldn't achieve it , Is there any way to achieve exactly like below?

![receipt2](https://user-images.githubusercontent.com/5355180/95572462-45bf4800-0a2a-11eb-9167-1f1336cfe9f4.jpg)

**Comment by prasanthsubendran** [comment]
I also had this need and figured out how to do. Thought sharing that here as it might be useful for someone. 

You can achieve this requirement using `bluetooth.writeBytes()` and `bluetooth.write()`
`bluetooth.writeBytes()` can be used to set alignments (Left, Center, Right)  and font sizes (0,1,2,3,4)
`bluetooth.write()` can be used to print text in String format. 
 
For eg: 
```
bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x0])); // 1- only bold text
bluetooth.writeBytes(Uint8List.fromList([0x1b, 0x61, 0x00])); //ESC_ALIGN_LEFT

bluetooth.write('Qty');
bluetooth.write(" ");  //your own spacing
bluetooth.write('Item');
bluetooth.write("   ");  //your own spacing
bluetooth.write('Price');
bluetooth.write("    ");  //your own spacing
bluetooth.write('Total');

bluetooth.printNewLine();
```

Input Bytes details for other font sizes: 

```
bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x03])); // 0- normal size text
bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x08])); // 1- only bold text
bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x20])); // 2- bold with medium text
bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x10])); //3- bold with large text
bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x30]));  // 4- strong text
```

**Comment by enricoirawan** [comment]
bluetooth.writeBytes(Uint8List.fromList([0x1b, 0x61, 0x00])); //ESC_ALIGN_LEFT

Can you tell me what about make ESC_ALIGN_RIGHT?

**Comment by enricoirawan** [comment]
> I also had this need and figured out how to do. Thought sharing that here as it might be useful for someone.
> 
> You can achieve this requirement using `bluetooth.writeBytes()` and `bluetooth.write()`
> `bluetooth.writeBytes()` can be used to set alignments (Left, Center, Right) and font sizes (0,1,2,3,4)
> `bluetooth.write()` can be used to print text in String format.
> 
> For eg:
> 
> ```
> bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x0])); // 1- only bold text
> bluetooth.writeBytes(Uint8List.fromList([0x1b, 0x61, 0x00])); //ESC_ALIGN_LEFT
> 
> bluetooth.write('Qty');
> bluetooth.write(" ");  //your own spacing
> bluetooth.write('Item');
> bluetooth.write("   ");  //your own spacing
> bluetooth.write('Price');
> bluetooth.write("    ");  //your own spacing
> bluetooth.write('Total');
> 
> bluetooth.printNewLine();
> ```
> 
> Input Bytes details for other font sizes:
> 
> ```
> bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x03])); // 0- normal size text
> bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x08])); // 1- only bold text
> bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x20])); // 2- bold with medium text
> bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x10])); //3- bold with large text
> bluetooth.writeBytes(Uint8List.fromList([0x1B, 0x21, 0x30]));  // 4- strong text
> ```

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.

**Comment by Ashbuhrz** [comment]
You can also achieve this by formating.

here is the example code:

```
  for (var e in invoice.item) {
    double total = e.regularPice * e.localQuantity;
    await bluetooth.print4Column(
      e.name.trim(),
      "${e.localQuantity} Pc",
      "${e.regularPice}",
      total.toStringAsFixed(2),
      Size.bold.val,
      format: "%-20s %-8s %8s %8s %n",
    );
  }
```
