### ISSUE TITLE
Is it support xprinter?

### ISSUE THREAD

**Issue by lyseiha** [kakzaki/blue_thermal_printer#59]

**Comment by harshilishere** [comment]
I would also like to know if xprinter thermal printer specifically this one works or not:

[https://www.amazon.in/Wizzit-Xprinter-Rechargeable-Bluetooth-Interface/dp/B08RK2VYQT/ref=sr_1_58?crid=2AN8TZIMUR5E2&dchild=1&keywords=rs232+thermal+printer&qid=1630491971&sprefix=rs232+therm%2Caps%2C280&sr=8-58]

**Comment by brownAddict** [comment]
I can confirm that this package works for xprinter (I am not fully sure of that one you linked).

These 2 printers below have been tested.
https://www.amazon.in/Wireless-Bluetooth-Thermal-Printer-Chargeable/dp/B08CGC65C2/ref=sr_1_11?dchild=1&keywords=thermal+printer&qid=1634406746&qsid=260-4248606-6295911&sr=8-11&sres=B09DWVH1R4%2CB09CD75DRD%2CB08X4DBGH1%2CB07CYQ6KY7%2CB07R958X1Y%2CB07F1PZZJG%2CB08X4DLBWR%2CB0991TNFT1%2CB07JVL4BP2%2CB07S8H62NW%2CB08CGC65C2%2CB07KS5JN36%2CB07SBNV7K6%2CB07CXGW682%2CB07RWJGN8C%2CB08JTY9DC9%2CB08RK2VYQT%2CB083TPYKK5%2CB08ZCQCX5H%2CB09HNLD8DG&srpt=PRINTER

https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww-konga-com-res.cloudinary.com%2Fw_auto%2Cf_auto%2Cfl_lossy%2Cdpr_auto%2Cq_auto%2Fmedia%2Fcatalog%2Fproduct%2FQ%2FN%2F61028_1597642680.jpg&imgrefurl=https%3A%2F%2Fwww.konga.com%2Fproduct%2Fxprinter-bluetooth-pos-printer-4877874&tbnid=idibxiK0_tLPeM&vet=12ahUKEwitrtu3v8_zAhWT0YUKHaO_DHYQMygBegUIARDXAQ..i&docid=Jsx5rVWsaPtjNM&w=500&h=500&q=bluetooth%20xprinter&client=safari&ved=2ahUKEwitrtu3v8_zAhWT0YUKHaO_DHYQMygBegUIARDXAQ

**Comment by YahalomsGuy** [comment]
> m not fully sure of that one y

can you confirm that you printed over Bluetooth?
I am trying to print to Xprinter XP-365B on Bluetooth and nothing happans , I can connect, but when I press "Print" on the example app, it just doesnt print , for full in for see issue #152 I have just opened.

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
