### ISSUE TITLE
French accents

### ISSUE THREAD

**Issue by JoanRodri** [kakzaki/blue_thermal_printer#60]
Hello, 
I would like to print in french but the accents create weird symbols. How could I fix this please ?

**Comment by Ehouman09** [comment]
Bonjour @JoanRodri , as tu pu trouver une solution pour les caractères accentués ?

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
