### ISSUE TITLE
how to print 80mm paper size

### ISSUE THREAD

**Issue by dihsarjr** [kakzaki/blue_thermal_printer#64]
how to print 80mm print in this package

**Comment by thantsin4ung** [comment]
I have same issues.
I want to print width 100 and height 150, 80mm printer.
`Map<String, dynamic> config = Map();
                            config['width'] = 100;
                            config['height'] = 150;
                            config['gap'] = 2;
list.add(LineText(type: LineText.TYPE_IMAGE, x:10, y:10, content: base64Image, height: 150, width: 100, ));`
print out result is normal. how can i fix this case.
Suggest for me solution.
Thanks

**Comment by tehsunnliu** [comment]
I guess there's no support for 80mm printer.

**Comment by dihsarjr** [comment]
yes

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
