### ISSUE TITLE
Can't print Arabic text

### ISSUE THREAD

**Issue by thevirusone** [kakzaki/blue_thermal_printer#65]

**Comment by fatimaown93** [comment]
did you find a solution for it ? because I'm facing the same problem now

**Comment by tanlocle0495** [comment]
hello have any solution or update for this issue

**Comment by bluemix** [comment]
Please check this solution:
https://github.com/kakzaki/blue_thermal_printer/issues/82#issuecomment-1048964685

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
