### ISSUE TITLE
Encoding printer character suport

### ISSUE THREAD

**Issue by ismaeladriano** [kakzaki/blue_thermal_printer#7]
Incorrect printout when has special characters.

**Comment by bossahack** [comment]
for example GBK utf8
THREAD.write(message.getBytes("GBK"));

**Comment by 792266344** [comment]
> for example GBK utf8
> THREAD.write(message.getBytes("GBK"));
But,The method write() can't set fontsize,printCustom() can do it
So,How to print GBK and also can set fontsize

**Comment by 792266344** [comment]
the questions that print different fontsizes and encode are resolved with change anthor's codes
Now,I have a new question,what's the "new byte[] { 0x1b, 'a', 0x02 }" mean,how does it can set fontsize and content align,please teach me how to use it or share me some courses ,THANKS!!!

**Comment by Alekie74** [comment]
how can I tie the connected printer so that no need to connect every time the application is loaded?

**Comment by 792266344** [comment]
> how can I tie the connected printer so that no need to connect every time the application is loaded?

use bluetooth，keep bluetooth always open and connect to printer
