### ISSUE TITLE
prints the QR and horizontal Text

### ISSUE THREAD

**Issue by jorgencnc** [kakzaki/blue_thermal_printer#73]
Hello friends, could you help me how I can use the library that prints the QR and horizontal Text. Thank you very much for your support

![imagen](https://user-images.githubusercontent.com/17854197/113612991-2e969700-9616-11eb-8911-4097f3d7e6c9.png)

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
