### ISSUE TITLE
Flutter Print UTF-8 (Vietnamese) on bluetooth thermal printer using “blue_thermal_printer 1.1.3”

### ISSUE THREAD

**Issue by anpham293** [kakzaki/blue_thermal_printer#76]
I have a trouble, here is my code:
```

  if (isConnected) {
    final f = NumberFormat("#,###", "vi_VN");
    bluetooth.printCustom("CÔNG TY CỔ PHẦN", 3, 1);
  }
```
The printer worked properly but can not print UTF-8 Unicode characters:

`The result: "C NG TY C  PH N"`
I also found charset in plugin lib:

 ```
Future<dynamic> printCustom(String message, int size, int align,
      {String? charset}) =>
  _channel.invokeMethod('printCustom', {
    'message': message,
    'size': size,
    'align': align,
    'charset': charset
  });
```
And replace charset by "UTF-8" but nothing change:

 ```
Future<dynamic> printCustom(String message, int size, int align,
      {String? charset}) =>
  _channel.invokeMethod('printCustom', {
    'message': message,
    'size': size,
    'align': align,
    'charset': "UTF-8"
  });
```
Hope your help, thank you so much!

**Comment by tcd93** [comment]
This also depends on your printer, not every printer support UTF-8 encoding

Vietnamese restaurants usually use SUNMI POS printer which DOES support it, but it does not follow the ESC/POS standard command

You have to customize your print methods such as `printLeftRight` to input special command before writing:
```java
// PrinterCommands.java
static final byte[] ENC_UTF8 = new byte[] {0x1C, 0x43, (byte) 0xFF}; // SUMMI printer specific codes
...
THREAD.write(PrinterCommands.ENC_UTF8); // add this line before writing
```
This is the link to the developer guide of SUNMI: https://file.cdn.sunmi.com/SUNMIDOCS/Sunmi-Printing-Service-ENCN.pdf

For ESC/POS compliant devices the command hex code is `1C 28 43 02 00 30 m` ([FS ( C](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=337#fs_lparen_cc_fn48), `m` depends on the model)

**Comment by JRakhimov** [comment]
@tcd93 Hi, can you tell, please, how to print cyrillic symbols?

**Comment by tcd93** [comment]
@JRakhimov 
Took a look in the description and seems like it support cyrillic characters

Try adding the command [1B, 74, 17](https://aures-support.com/DATA/drivers/Imprimantes/Commande%20ESCPOS.pdf)
```java
// PrinterCommands.java
static final byte[] ENC_CYRIL = new byte[] {0x1B, 0x74, 0x17};
...
// in PrintLeftRight, add this to the begining
Thread.Write(PrinterCommands.ENC_CYRIL)
```
![image](https://user-images.githubusercontent.com/17901180/124254873-b75c9a80-db53-11eb-8695-ef7ff2ba7084.png)

**Comment by JRakhimov** [comment]
@tcd93 Amazing, works great, thank you

**Comment by JRakhimov** [comment]
P.S. charset should be "windows-1251"

**Comment by ebrahimmansur** [comment]
> This also depends on your printer, not every printer support UTF-8 encoding
> 
> Vietnamese restaurants usually use SUNMI POS printer which DOES support it, but it does not follow the ESC/POS standard command
> 
> You have to customize your print methods such as `printLeftRight` to input special command before writing:
> 
> ```java
> // PrinterCommands.java
> static final byte[] ENC_UTF8 = new byte[] {0x1C, 0x43, (byte) 0xFF}; // SUMMI printer specific codes
> ...
> THREAD.write(PrinterCommands.ENC_UTF8); // add this line before writing
> ```
> 
> This is the link to the developer guide of SUNMI: https://file.cdn.sunmi.com/SUNMIDOCS/Sunmi-Printing-Service-ENCN.pdf
> 
> For ESC/POS compliant devices the command hex code is `1C 28 43 02 00 30 m` ([FS ( C](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=337#fs_lparen_cc_fn48), `m` depends on the model)

where is this code implemented  -> which  file
