### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by nirranthea** [kakzaki/blue_thermal_printer#81]
When printer was restarted, I got `java.io.IOException: Broken pipe` when printing.
How to catch this exception ? because when I tried theese, it was'nt detected as exception

```
printer.printCustom('anything', 1, 1).onError((error, stactTrace) {
   //do something
});

printer.printCustom('anything', 1, 1).catchError((onError) {
   //do something
});
```

**Comment by rishirizz** [comment]
I am also facing the same issue.

**Comment by swarup13** [comment]
facing same issue

**Comment by danny2585** [comment]
was this problem fixed?

**Comment by tegarnugroho** [comment]
we can't catch java.io.IOException: Broken pipe from flutter plugin, because in native code it doesn't return result.error when that exception occurred

**Comment by danny2585** [comment]
the solution that I implemented was a bit drastic

I store the printer info in internal storage with shared_preferences, then build a BluetoothDevice type variable and finally disconnect and connect the printer, in this way it is faster when printing and must be secured with a (Try Catch) for obvious reasons below I leave my code


```
 await bluetoothThermal.isConnected.then((isConnected) async {
            if (!isConnected) {
              try {
                await bluetoothThermal
                    .connect(printer)
                    .timeout(Duration(seconds: 4));
              } on PlatformException catch (e) {
                debugPrint('Catch printReceipt in printer OFF $e');
                
                printerInicialized = false;
              }

              printerInicialized = true;
            } else {
              try {
                await bluetoothThermal.disconnect();
                await Future<void>.delayed(Duration(microseconds: 500));
                await bluetoothThermal.connect(printer);
              } catch (e) {
                print('//////////////// printReceipt ${e.code}');
                
              }
            }
          });
```

**Comment by danny2585** [comment]
in my case the problem was caused by lack of time so I just added

`await Future<void>.delayed(Duration(microseconds: 500));`

hope it works for you too
