### ISSUE TITLE
Please provide a good Api doc with good explanation 

### ISSUE THREAD

**Issue by ebrahimmansur** [kakzaki/blue_thermal_printer#83]
This does not provide any information on how to use the api , only few api are self explanatory (which  is dangerous - not exactly sure with it does only assumption)

![Screen Shot 2021-06-07 at 8 46 17 AM](https://user-images.githubusercontent.com/34646327/120972150-b9f2ec80-c76d-11eb-94e4-9996a8d76b59.png)

- please  provide the same structure as this image blow

![Screen Shot 2021-06-07 at 8 49 45 AM](https://user-images.githubusercontent.com/34646327/120972276-ddb63280-c76d-11eb-8fe1-65628e9db5b5.png)

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
