### ISSUE TITLE
(MethodCall) => Null' is not a subtype of type '((MethodCall) => Future<dynamic>)?'

### ISSUE THREAD

**Issue by zeed-dev** [kakzaki/blue_thermal_printer#84]
════════ Exception caught by widgets library ═══════════════════════════════════
type '(MethodCall) => Null' is not a subtype of type '((MethodCall) => Future<dynamic>)?' in type cast
The relevant error-causing widget was

STUCK IN THIS issue please help.

**Comment by 22syamsudar** [comment]
same with... 
:(

**Comment by zeed-dev** [comment]
To fix it, replace default constructor in 34 line of blue_thermal_printer.dart from this:

  BlueThermalPrinter._() {
    _channel.setMethodCallHandler((MethodCall call) {
      _methodStreamController.add(call);
    } as Future<dynamic> Function(MethodCall)?);
  }

to this:

BlueThermalPrinter._() {
    _channel.setMethodCallHandler((MethodCall call) async{
      _methodStreamController.add(call);
    });
  }
