### ISSUE TITLE
Special characters for printing

### ISSUE THREAD

**Issue by minhnhatvdl** [kakzaki/blue_thermal_printer#87]
Hello,

I use a themal printer Bixolon SPP-R210. I have a problem when i want to print frech special characters (àèé...).
I tested with utf-8 but not working.

Has anyone encountered the same situation as me?

My thanks

**Comment by VetrivelDevOps** [comment]
It won't support special characters. To solve this issue, Need to convert text to image & print image

**Comment by ebrahimmansur** [comment]
how to convert text to image in dart, have you got a gist of code ? for  example"hello " as image

**Comment by VetrivelDevOps** [comment]
I got. But it's not working as we expected

**Comment by Cadcom** [comment]
:))

**Comment by Lazizbek97** [comment]
Hello, is this issue been resolved? I'm having also the same error....

**Comment by fayyaztech** [comment]
`

List<Uint8List> imgList = [];
        late Uint8List imageInt;
        late im.Image? receiptImg;

        //image from Asset
        ByteData bytesAsset = await rootBundle.load("assets/election_mark.png");
        Uint8List imageBytesFromAsset = bytesAsset.buffer
            .asUint8List(bytesAsset.offsetInBytes, bytesAsset.lengthInBytes);

        bluetooth.printImageBytes(imageBytesFromAsset); //image from Asset

        //Main heading
        imageInt = await getBillImage("${Headings.election}\n", fontSize: 40);
        receiptImg = im.decodePng(imageInt);
        for (var i = 0; i <= receiptImg!.height; i += 200) {
          im.Image cropedReceiptImg = im.copyCrop(receiptImg, 0, i, 470, 200);
          Uint8List bytes = im.encodePng(cropedReceiptImg) as Uint8List;
          imgList.add(bytes);
        }

        //Party name
        imageInt = await getBillImage("${Headings.partyLine}\n", fontSize: 30);
        receiptImg = im.decodePng(imageInt);
        for (var i = 0; i <= receiptImg!.height; i += 200) {
          im.Image cropedReceiptImg = im.copyCrop(receiptImg, 0, i, 470, 200);
          Uint8List bytes = im.encodePng(cropedReceiptImg) as Uint8List;
          imgList.add(bytes);
        }

        //candidate
        imageInt = await getBillImage("${Headings.candidate}\n", fontSize: 35);
        receiptImg = im.decodePng(imageInt);
        for (var i = 0; i <= receiptImg!.height; i += 200) {
          im.Image cropedReceiptImg = im.copyCrop(receiptImg, 0, i, 470, 200);
          Uint8List bytes = im.encodePng(cropedReceiptImg) as Uint8List;
          imgList.add(bytes);
        }

        //main content
        imageInt = await getBillImage(voterString(widget.data), fontSize: 30);
        receiptImg = im.decodePng(imageInt);
        for (var i = 0; i <= receiptImg!.height; i += 200) {
          im.Image cropedReceiptImg = im.copyCrop(receiptImg, 0, i, 470, 200);
          Uint8List bytes = im.encodePng(cropedReceiptImg) as Uint8List;
          imgList.add(bytes);
          bluetooth.printNewLine();
        }

        bluetooth.printNewLine();

        for (var element in imgList) {
          bluetooth.printImageBytes(element);
        }`



replace **Headings** with your special char and print it works. and you also can add **images** from **assets** if you wish to print logo

**Comment by 15ground** [comment]
> Uint8List

Can u provide getBillImage sir? Please help me!
