### ISSUE TITLE
Something error?

### ISSUE THREAD

**Issue by sabsab-yeng** [kakzaki/blue_thermal_printer#88]
../../flutter/.pub-cache/hosted/pub.dartlang.org/blue_thermal_printer-1.1.3/lib/blue_thermal_printer.dart:37:7: Error: The argument type 'Future<dynamic>? Function(MethodCall)?' can't be assigned to the parameter type 'Future<dynamic> Function(MethodCall)?' because 'Future<dynamic>?' is nullable and 'Future<dynamic>' isn't.
 - 'Future' is from 'dart:async'.
 - 'MethodCall' is from 'package:flutter/src/services/message_codec.dart' ('../../flutter/packages/flutter/lib/src/services/message_codec.dart').
    } as Future<dynamic>? Function(MethodCall)?);
      ^

**Comment by giullianocht** [comment]
https://github.com/kakzaki/blue_thermal_printer/pull/79
