### ISSUE TITLE
The plugin blue_thermal_printer use a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by swarup13** [kakzaki/blue_thermal_printer#96]
The plugins `blue_thermal_printer, ext_storage` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2
embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.

**Comment by kakzaki** [comment]
i hope it will be resolved at 1.1.5

**Comment by swarup13** [comment]
Thank you so much @kakzaki
