### ISSUE TITLE
error: unknown receiver 'FlutterBluePlugin'; did you mean 'FluttertoastPlugin'?

### ISSUE THREAD

**Issue by swarup13** [kakzaki/blue_thermal_printer#97]
Xcode's output:
↳
    /Users/swarupbhanjachowdhury/Development/flutter/dineordercc_flutter/ios/Runner/GeneratedPluginRegistrant.m:84:4: error: unknown receiver 'FlutterBluePlugin'; did you mean 'FluttertoastPlugin'?
      [FlutterBluePlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterBluePlugin"]];
       ^~~~~~~~~~~~~~~~~
       FluttertoastPlugin
    In module 'fluttertoast' imported from /Users/swarupbhanjachowdhury/Development/flutter/dineordercc_flutter/ios/Runner/GeneratedPluginRegistrant.m:34:
    /Users/swarupbhanjachowdhury/Development/flutter/dineordercc_flutter/build/ios/Debug-iphonesimulator/fluttertoast/fluttertoast.framework/Headers/FluttertoastPlugin.h:3:12: note: 'FluttertoastPlugin' declared here
    @interface FluttertoastPlugin : NSObject<FlutterPlugin>

**Comment by jorgefdezblanco** [comment]
como puedo resolver ese error

**Comment by gbloggs** [comment]
This error is killing my iOS build.
Built with Xcode 13.
blue_thermal_printer: 1.1.7

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 12.0 21A5506j darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.57.0)
[✓] Connected device (1 available)

• No issues found!
