### ISSUE TITLE
How can we set width for elements of ```printNColumn()```?

### ISSUE THREAD

**Issue by rishirizz** [kakzaki/blue_thermal_printer#99]
I was trying to give proper spacing to the column elements using ```print4Column()``` but i am not sure how to do that. The ```format``` property takes different parameters but not much documentation has been provided to use that correctly. Can anyone help ?

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
